INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CONSTELLATION_MAPPING constellation_mapping)

FIND_PATH(
    CONSTELLATION_MAPPING_INCLUDE_DIRS
    NAMES constellation_mapping/api.h
    HINTS $ENV{CONSTELLATION_MAPPING_DIR}/include
        ${PC_CONSTELLATION_MAPPING_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CONSTELLATION_MAPPING_LIBRARIES
    NAMES gnuradio-constellation_mapping
    HINTS $ENV{CONSTELLATION_MAPPING_DIR}/lib
        ${PC_CONSTELLATION_MAPPING_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/constellation_mappingTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CONSTELLATION_MAPPING DEFAULT_MSG CONSTELLATION_MAPPING_LIBRARIES CONSTELLATION_MAPPING_INCLUDE_DIRS)
MARK_AS_ADVANCED(CONSTELLATION_MAPPING_LIBRARIES CONSTELLATION_MAPPING_INCLUDE_DIRS)
