INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CONSTELATION_MAPPING_MODULE constelation_mapping_module)

FIND_PATH(
    CONSTELATION_MAPPING_MODULE_INCLUDE_DIRS
    NAMES constelation_mapping_module/api.h
    HINTS $ENV{CONSTELATION_MAPPING_MODULE_DIR}/include
        ${PC_CONSTELATION_MAPPING_MODULE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CONSTELATION_MAPPING_MODULE_LIBRARIES
    NAMES gnuradio-constelation_mapping_module
    HINTS $ENV{CONSTELATION_MAPPING_MODULE_DIR}/lib
        ${PC_CONSTELATION_MAPPING_MODULE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/constelation_mapping_moduleTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CONSTELATION_MAPPING_MODULE DEFAULT_MSG CONSTELATION_MAPPING_MODULE_LIBRARIES CONSTELATION_MAPPING_MODULE_INCLUDE_DIRS)
MARK_AS_ADVANCED(CONSTELATION_MAPPING_MODULE_LIBRARIES CONSTELATION_MAPPING_MODULE_INCLUDE_DIRS)
